// `hono-svelte init` + `hono-svelte doctor` helpers.
//
// The package exposes pure helpers (`initFiles`, `doctorChecks`) so they can
// be unit-tested; the thin CLI wrapper lives in `src/cli.ts` (compiled to
// `dist/cli.js`, invoked via the `hono-svelte` bin).
//
// Runtime note: `init` writes plain text files only — no install, no network.
// It works identically under `bunx` (bun), `npx` (npm) and `pnpm dlx`.
// The generated app targets bun first (`bun install`, `bun run dev/build/start`);
// npm still works since every script shells out to `vite` / `node`.

import { existsSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";

export type InitFile = { path: string; content: string; skipIfExists: boolean };

export type InitFlavor = "minimal" | "full";

const ENV_DTS = `// Entry names are generated by \`pages({ dts: true })\` into
// \`src/hono-svelte-entries.d.ts\` (see vite.config.ts). \`c.render()\` only
// accepts those names — a typo fails the typecheck.
 /// <reference path="./hono-svelte-entries.d.ts" />
`;

const VITE_CONFIG = `// Bun-first: run everything with bun (bun run dev/build/start).
// NOTE: @hono/vite-build is ESM-only. Bun loads vite.config.ts natively as
// ESM, so the "/bun" subpath works. Under plain node, Vite loads the config
// through require() and "/bun" fails — use vite.config.node.ts + npm scripts
// (build:node / start:node) for node.
import build from "@hono/vite-build/bun";
import devServer from "@hono/vite-dev-server";
import bunAdapter from "@hono/vite-dev-server/bun";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { pages } from "hono-svelte/vite";
import { resolve } from "node:path";
import { defineConfig } from "vite";

const appPages = pages({ dts: true });

export default defineConfig(({ command, mode }) => {
  if (mode === "client") {
    return {
      plugins: [svelte(), appPages],
      build: {
        rollupOptions: {
          input: { ...appPages.input(), styles: resolve("src/styles.css") },
          output: {
            entryFileNames: "static/[name].js",
            chunkFileNames: "static/chunks/[name]-[hash].js",
            assetFileNames: "static/[name][extname]",
          },
        },
      },
    };
  }

  if (command === "serve") {
    return {
      plugins: [
        svelte(),
        appPages,
        devServer({ entry: "src/routes/index.ts", adapter: bunAdapter() }),
      ],
    };
  }

  return {
    plugins: [svelte(), appPages, build({ entry: "src/routes/index.ts", staticRoot: "./dist" })],
  };
});
`;

const PACKAGE_JSON = `{
  "name": "my-hono-svelte-app",
  "type": "module",
  "private": true,
  "engines": {
    "bun": ">=1.4",
    "node": ">=26"
  },
  "scripts": {
    "dev": "vite",
    "build": "bun run build:client && bun run build:server",
    "build:client": "vite build --mode client",
    "build:server": "vite build --mode production",
    "typecheck": "tsc --noEmit",
    "start": "bun ./dist/index.js",
    "start:node": "node ./dist/index.js"
  },
  "dependencies": {
    "hono": "^4",
    "hono-svelte": "latest",
    "svelte": "^5"
  },
  "devDependencies": {
    "@hono/vite-build": "^1",
    "@hono/vite-dev-server": "^0",
    "@sveltejs/vite-plugin-svelte": "^7",
    "@types/node": "^26",
    "typescript": "^7",
    "vite": "^8"
  }
}
`;

const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "skipLibCheck": true,
    "lib": ["ESNext", "DOM", "DOM.Iterable"],
    "types": ["vite/client", "node"]
  },
  "include": ["src/**/*", "vite.config.ts"],
  "exclude": ["node_modules", "dist"]
}
`;

const GITIGNORE_TEXT = `node_modules
dist
`;

const INDEX_SVELTE = `<main>
  <h1>Welcome</h1>
  <p><a href="/hello">Say hello</a></p>
</main>
`;

const HELLO_SVELTE = `<script lang="ts">
  let { name }: { name?: string } = $props();
</script>

<main>
  <h1>Hello, {name ?? "stranger"}!</h1>
  <p><a href="/">Back home</a></p>
</main>
`;

const STYLES_CSS = `body {
  font-family: system-ui, sans-serif;
  margin: 0;
}

main {
  max-width: 640px;
  margin: 4rem auto;
  padding: 0 1rem;
}
`;

const FULL_LIB_AUTH = `import type { Context } from "hono";
import { getCookie } from "hono/cookie";

export const SESSION_COOKIE = "hono_demo_session";
export const SESSION_VALUE = "authenticated";

export function hasSession(c: Context): boolean {
  return getCookie(c, SESSION_COOKIE) === SESSION_VALUE;
}
`;

const FULL_MW_AUTH = `import { createMiddleware } from "hono/factory";
import { hasSession } from "../lib/auth";

export function requireSession() {
  return createMiddleware(async (c, next) => {
    if (!hasSession(c)) return c.redirect("/auth");
    return next();
  });
}
`;

const FULL_PAGE_AUTH = `<main>
  <h1>Sign in</h1>
  <form action="/auth/login" method="post">
    <div>
      <label for="email">Email</label>
      <input id="email" name="email" type="email" required />
    </div>
    <div>
      <label for="password">Password</label>
      <input id="password" name="password" type="password" required />
    </div>
    <button type="submit">Sign in</button>
  </form>
  <p>Any email + password works.</p>
  <p><a href="/">Back home</a></p>
</main>
`;

const FULL_PAGE_DASH_INDEX = `<script lang="ts">
  import { hc } from "hono/client";
  import type { AppType } from "../../routes";

  const client = hc<AppType>("/");

  let count = $state(0);
  let time = $state<string | null>(null);

  async function fetchTime() {
    const res = await client.api.clock.$get();
    if (res.ok) time = (await res.json()).now;
  }
</script>

<div>
  <p>Count: {count}</p>
  <button type="button" onclick={() => (count += 1)}>Increment</button>
  <p>
    <button type="button" onclick={fetchTime}>Fetch time</button>
  </p>
</div>
`;

const FULL_PAGE_DASH_PAGE1 = `<section>
  <h2>Page 1 content</h2>
  <p>Same layout, zero JS.</p>
  <p><a href="/dashboard">Back to overview</a></p>
</section>
`;

const FULL_PAGE_DASH_LAYOUT = `<script lang="ts">
  import type { Snippet } from "svelte";

  type Props = { title?: string; description?: string; children: Snippet };
  let { title = "Dashboard", description = "", children }: Props = $props();
</script>

<main>
  <header>
    <h1>{title}</h1>
  </header>
  {@render children()}
</main>
`;

const MIN_ROUTES_INDEX = `import { Hono } from "hono";
import { shell } from "hono-svelte";

const app = new Hono().use("/*", shell({ title: "My App" }));

app.get("/", (c) => c.render("index"));
app.get("/hello", (c) => c.render("hello", { data: { name: "Ada" } }));

export default app;
`;

export function initFiles(flavor: InitFlavor = "minimal"): InitFile[] {
  const base: InitFile[] = [
    { path: "package.json", content: PACKAGE_JSON, skipIfExists: true },
    { path: "tsconfig.json", content: TSCONFIG_JSON, skipIfExists: true },
    { path: ".gitignore", content: GITIGNORE_TEXT, skipIfExists: true },
    { path: "src/env.d.ts", content: ENV_DTS, skipIfExists: true },
    { path: "vite.config.ts", content: VITE_CONFIG, skipIfExists: true },
    { path: "src/styles.css", content: STYLES_CSS, skipIfExists: true },
    { path: "src/pages/index.svelte", content: INDEX_SVELTE, skipIfExists: true },
    { path: "src/pages/hello.svelte", content: HELLO_SVELTE, skipIfExists: true },
    { path: "src/routes/index.ts", content: MIN_ROUTES_INDEX, skipIfExists: true },
  ];
  if (flavor === "minimal") return base;
  return [...base, ...fullFlavorFiles()];
}

function fullFlavorFiles(): InitFile[] {
  const dashboardRoutes = `import { Hono } from "hono";
import { requireSession } from "../middleware/auth";

const app = new Hono()
  .get("/", requireSession(), (c) =>
    c.render("dashboard/index", {
      data: {
        title: "Your space is ready.",
        description: "Counter + clock via typed RPC.",
      },
    }),
  )
  .get("/page1", requireSession(), (c) =>
    c.render("dashboard/page1", {
      data: { title: "Page 1", description: "A second page, same layout." },
    }),
  );

export default app;
`;
  const siteRoutes = `import { Hono } from "hono";
import { hasSession } from "../lib/auth";

const app = new Hono().get("/", async (c) => {
  if (hasSession(c)) return c.redirect("/dashboard");
  return c.render("index");
});

export default app;
`;
  const authRoutes = `import { Hono } from "hono";
import { setCookie } from "hono/cookie";
import { hasSession, SESSION_COOKIE, SESSION_VALUE } from "../lib/auth";

const app = new Hono();

app.get("/", (c) => {
  if (hasSession(c)) return c.redirect("/dashboard");
  return c.render("auth");
});

app.post("/login", async (c) => {
  const body = await c.req.parseBody();
  const email = String(body.email ?? "");
  const password = String(body.password ?? "");
  if (!email.includes("@") || !password) return c.redirect("/auth?error=invalid");
  setCookie(c, SESSION_COOKIE, SESSION_VALUE, {
    maxAge: 3600,
    path: "/",
    httpOnly: true,
    sameSite: "Lax",
  });
  return c.redirect("/dashboard");
});

app.post("/logout", (c) => {
  setCookie(c, SESSION_COOKIE, "", { maxAge: 0, path: "/" });
  return c.redirect("/");
});

export default app;
`;
  const apiRoutes = `import { Hono } from "hono";
import { hasSession } from "../lib/auth";

const app = new Hono().get("/clock", (c) => {
  if (!hasSession(c)) return c.json({ error: "Not authenticated" }, 401);
  return c.json({ now: new Date().toISOString() });
});

export default app;
`;
  const appRoutes = `import { Hono } from "hono";
import { shell } from "hono-svelte";
import api from "./api";
import auth from "./auth";
import dashboard from "./dashboard";
import site from "./site";

const app = new Hono();

const routes = app
  .use("/*", shell({ title: "My App", lang: "en" }))
  .route("/", site)
  .route("/auth", auth)
  .route("/dashboard", dashboard)
  .route("/api", api);

export type AppType = typeof routes;

export default app;
`;
  return [
    { path: "src/lib/auth.ts", content: FULL_LIB_AUTH, skipIfExists: true },
    { path: "src/middleware/auth.ts", content: FULL_MW_AUTH, skipIfExists: true },
    { path: "src/routes/index.ts", content: appRoutes, skipIfExists: false },
    { path: "src/routes/site.ts", content: siteRoutes, skipIfExists: true },
    { path: "src/routes/auth.ts", content: authRoutes, skipIfExists: true },
    { path: "src/routes/dashboard.ts", content: dashboardRoutes, skipIfExists: true },
    { path: "src/routes/api.ts", content: apiRoutes, skipIfExists: true },
    { path: "src/pages/auth.svelte", content: FULL_PAGE_AUTH, skipIfExists: true },
    {
      path: "src/pages/dashboard/index.svelte",
      content: FULL_PAGE_DASH_INDEX,
      skipIfExists: true,
    },
    {
      path: "src/pages/dashboard/page1.svelte",
      content: FULL_PAGE_DASH_PAGE1,
      skipIfExists: true,
    },
    {
      path: "src/pages/dashboard/layout.svelte",
      content: FULL_PAGE_DASH_LAYOUT,
      skipIfExists: true,
    },
  ];
}

export type DoctorIssue = {
  /** Machine-readable code, e.g. "missing-dist". */
  code: string;
  message: string;
  fix: string;
};

export type DoctorOptions = {
  /** Root of the hono-svelte package (where `dist/` lives). @default cwd */
  packageRoot?: string;
  /** Root of the app being checked. @default cwd */
  appRoot?: string;
};

export function doctorChecks(opts: DoctorOptions = {}): DoctorIssue[] {
  const packageRoot = opts.packageRoot ? resolve(opts.packageRoot) : process.cwd();
  const appRoot = opts.appRoot ? resolve(opts.appRoot) : process.cwd();
  const issues: DoctorIssue[] = [];

  for (const file of ["dist/index.js", "dist/vite.js", "dist/index.d.ts", "dist/vite.d.ts"]) {
    if (!existsSync(join(packageRoot, file))) {
      issues.push({
        code: "missing-dist",
        message: `hono-svelte dist is missing (${file} not found). The package was not built.`,
        fix: "Run `npm run build` in the hono-svelte package directory.",
      });
      break;
    }
  }

  const viteConfig = join(appRoot, "vite.config.ts");
  if (!existsSync(viteConfig) && !existsSync(join(appRoot, "vite.config.js"))) {
    issues.push({
      code: "missing-vite-config",
      message: "No vite config found in the app.",
      fix: "Run `hono-svelte init` to scaffold one, or copy the README quick-start.",
    });
  }

  return issues;
}

export function checkAppLink(appRoot: string): DoctorIssue | null {
  const appLink = join(resolve(appRoot), "node_modules", "hono-svelte");
  if (!existsSync(join(appLink, "package.json"))) {
    return {
      code: "missing-link",
      message: `node_modules/hono-svelte is missing or a stale junction in ${appRoot}.`,
      fix: "Run `npm install` inside the app directory to recreate the file: link.",
    };
  }
  return null;
}

export function isSafeAppPath(appRoot: string, target: string): boolean {
  // NOTE: compare case-insensitively on Windows (C:\Users vs c:\users) and
  // accept both separators. `join("C:\\x", "src/a")` yields backslashes,
  // so checking `startsWith(root + "/")` always failed on win32 and `init`
  // refused every file.
  const root = resolve(appRoot);
  const abs = isAbsolute(target) ? target : resolve(root, target);
  const norm = (p: string) => p.replace(/\\/g, "/");
  const lower = (p: string) => (process.platform === "win32" ? p.toLowerCase() : p);
  const nRoot = lower(norm(root));
  const nAbs = lower(norm(abs));
  // Exact root itself is not a writable file, but treat as safe for symmetry
  // with the old check; callers only pass file paths.
  return nAbs === nRoot || nAbs.startsWith(nRoot + "/");
}

/**
 * Entry name for `hono-svelte add page`: no traversal, no absolute paths,
 * no null chars/backslashes, and never a `layout` (layouts are convention,
 * not pages). `"blog/post-1"` is valid.
 */
export function isValidPageName(name: string): boolean {
  if (!name || name.length > 200) return false;
  if (name.startsWith("/") || name.startsWith(".")) return false;
  if (name.includes("\\") || name.includes(String.fromCharCode(0))) return false;
  const parts = name.split("/");
  if (parts.some((p) => p.length === 0 || p === "." || p === "..")) return false;
  if (name === "layout" || name.endsWith("/layout")) return false;
  return true;
}

/** File + content written by `hono-svelte add page <name>` (null on invalid names). */
export function newPageFile(name: string, pagesDir = "src/pages"): InitFile | null {
  const clean = name.replace(/\.svelte$/, "");
  if (!isValidPageName(clean)) return null;
  const title = (clean.split("/").pop() ?? clean).replace(/[-_]/g, " ");
  const content =
    `<!-- src/pages/${clean}.svelte — created by \`hono-svelte add page\`.\n` +
    `     This page has no script tag, so it ships as plain HTML (zero JS).\n` +
    `     Add a script to hydrate it on the client, or declare \`export type Data\`\n` +
    `     in a module script for typed data. -->\n` +
    `<main>\n  <h1>${title}</h1>\n  <p>Edit src/pages/${clean}.svelte.</p>\n</main>\n`;
  return { path: `${pagesDir}/${clean}.svelte`, content, skipIfExists: true };
}
