// IDs of the virtual modules shared between the plugin (hono-svelte/vite)
// and the shell (hono-svelte). Nothing is written to disk: entries and the manifest
// are served in-memory as virtual modules.

const NULL = String.fromCharCode(0);

export const ENTRY_PREFIX = "virtual:hono-svelte/entry/";
export const ENTRY_RESOLVED_PREFIX = NULL + ENTRY_PREFIX;
export const MANIFEST_ID = "virtual:hono-svelte/manifest";
export const MANIFEST_RESOLVED = NULL + MANIFEST_ID;

export function entryVirtualId(entryName: string): string {
  return ENTRY_PREFIX + entryName;
}

export function entryResolvedId(entryName: string): string {
  return ENTRY_RESOLVED_PREFIX + entryName;
}

// Dev URL for the <script type='module'> generated by the shell.
// \0 becomes __x00__ in the URL served by the Vite dev server.
export function devEntryUrl(entryName: string): string {
  return "/@id/" + entryResolvedId(entryName).replace(NULL, "__x00__");
}
